import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors
from sqlalchemy.orm import Session
from app.models.database import Document, DocumentStatus
from app.models.models import QualityScorecard, AuditRecord

class ReportingService:
    """
    Generates regulatory compliance documents (PDF).
    """

    @staticmethod
    def generate_certificate(db: Session, job_id: str) -> io.BytesIO:
        """
        Generates a 'Certificate of Translation Accuracy' PDF.
        """
        # 1. Fetch Data
        doc = db.query(Document).filter(Document.id == job_id).first()
        if not doc:
            raise ValueError("Job not found")
        
        scorecard = db.query(QualityScorecard).filter(QualityScorecard.job_id == job_id).first()
        audit = db.query(AuditRecord).filter_by(job_id=job_id).first()
        
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        # --- Header ---
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(width / 2, height - 1.5 * inch, "Certificate of Translation Accuracy")
        
        c.setFont("Helvetica", 10)
        c.drawCentredString(width / 2, height - 1.8 * inch, "Generated by TransMax Control Tower")
        
        # --- Job Details ---
        y = height - 3 * inch
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1 * inch, y, "Processing Information")
        y -= 0.3 * inch
        
        c.setFont("Helvetica", 12)
        c.drawString(1 * inch, y, f"Job ID: {doc.id}")
        y -= 0.25 * inch
        c.drawString(1 * inch, y, f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
        y -= 0.25 * inch
        c.drawString(1 * inch, y, f"Source Language: {doc.source_language.upper()}")
        y -= 0.25 * inch
        c.drawString(1 * inch, y, f"Target Language: {doc.target_language.upper() if doc.target_language else 'N/A'}")
        y -= 0.25 * inch
        c.drawString(1 * inch, y, f"Status: {doc.status.value.upper() if hasattr(doc.status, 'value') else str(doc.status).upper()}")

        # --- Quality Summary ---
        y -= 0.75 * inch
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1 * inch, y, "Quality & Governance Metrics")
        y -= 0.3 * inch
        
        c.setFont("Helvetica", 12)
        if scorecard:
            c.drawString(1 * inch, y, f"Critical Defects: {scorecard.critical_defect_count} (PASS)")
            y -= 0.25 * inch
            c.drawString(1 * inch, y, f"Major Defects: {scorecard.major_defect_count}")
            y -= 0.25 * inch
            c.drawString(1 * inch, y, f"Semantic Dirft Score: {scorecard.semantic_drift_score:.2f} / 100")
        else:
            c.drawString(1 * inch, y, "No Quality Scorecard available.")
            
        # --- Audit Integrity ---
        y -= 0.75 * inch
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1 * inch, y, "Audit Integrity Proof")
        y -= 0.3 * inch
        c.setFont("Courier", 10)
        if audit:
            c.drawString(1 * inch, y, f"Chain Head Hash: {audit.chain_head_hash}")
            y -= 0.2 * inch
            c.drawString(1 * inch, y, f"Audit ID: {audit.audit_id}")
        else:
            c.drawString(1 * inch, y, "Audit Trail Pending Finalization.")

        # --- Signature / Footer ---
        y = 1.5 * inch
        c.setStrokeColor(colors.black)
        c.line(1 * inch, y, width - 1 * inch, y)
        c.setFont("Helvetica-Oblique", 10)
        c.drawCentredString(width / 2, y - 0.2 * inch, "System Generated Signature - Tamper Evident")
        
        c.save()
        buffer.seek(0)
        return buffer
