"""Add_models_pgvector_audit

Revision ID: 430291da76c3
Revises: 
Create Date: 2026-01-17 14:51:13.794421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '430291da76c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('language_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('script_direction', sa.String(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id')
    )
    op.create_table('translation_glossaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'DEEPL', 'GOOGLE', 'AZURE', name='translationprovider'), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVIEW_REQUIRED', 'APPROVED', name='translationstatus'), nullable=True),
    sa.Column('audit_trail_id', sa.UUID(), nullable=True),
    sa.Column('formality', sa.String(), nullable=True),
    sa.Column('preserve_formatting', sa.Boolean(), nullable=True),
    sa.Column('enable_glossary', sa.Boolean(), nullable=True),
    sa.Column('glossary_id', sa.UUID(), nullable=True),
    sa.Column('enable_back_translation', sa.Boolean(), nullable=True),
    sa.Column('quality_check_enabled', sa.Boolean(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('completed_chunks', sa.Integer(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_trail_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('versions_snapshot', sa.JSON(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('output_hash', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('composite_scores', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('record_hash', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_audit_trail_id'), 'audit_records', ['audit_trail_id'], unique=False)
    op.create_index(op.f('ix_audit_records_input_hash'), 'audit_records', ['input_hash'], unique=False)
    op.create_table('chunk_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('back_translated_text', sa.Text(), nullable=True),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('issues_detected', sa.JSON(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('original_translation', sa.Text(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=True),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('terminology_accuracy', sa.Float(), nullable=True),
    sa.Column('total_issues', sa.Integer(), nullable=True),
    sa.Column('critical_issues', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Integer(), nullable=True),
    sa.Column('issue_details', sa.JSON(), nullable=True),
    sa.Column('terminology_mismatches', sa.JSON(), nullable=True),
    sa.Column('consistency_issues', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('chunks_requiring_review', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('report_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['translation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_reports')
    op.drop_table('chunk_translations')
    op.drop_index(op.f('ix_audit_records_input_hash'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_audit_trail_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_table('translation_memory')
    op.drop_table('translation_jobs')
    op.drop_table('translation_glossaries')
    op.drop_table('language_packs')
    # ### end Alembic commands ###
